### ISSUE TITLE
Milestone Report 1

### ISSUE THREAD

**Issue by emirhansarac29** [bounswe/bounswe2019group1#259]
Please check below parts regarding to Milestone Report 1, if you have completed it.
- [x] Executive Summary
- [x] List and status of deliverables
- [x] Evaluation of the status of deliverables and its impact on plan
- [x] Requirements.
- [x] API documentation.
- [x] Communication Plan
- [x] Project plan
- [x] User scenarios
- [x]  UI Design
- [x] Evaluation of tools and managing the project

A summary of coding work done by each team member:
- [x] Eray Kurtuluş
- [x] Ufuk Yılmaz
- [x] Yağmur Ceren Dardağan
- [x] Emirhan Saraç
- [x] İrem Üstünboyacıoğlu
- [x] Altay İnce
- [x] Abdullah Coşkun
- [ ] İlker Özkan
- [x] Mete Kurt
- [ ] Ömer Toptaş
