### ISSUE TITLE
Milestone Report 2

### ISSUE THREAD

**Issue by ycerend** [bounswe/bounswe2019group1#396]
The report for milestone 2 must be written until Saturday, November 30. Even if the deadline is December 1, Sunday 23:00, it will be better to finish earlier for the final check.  As we discussed in the meeting this week, the list of parts of the milestone report and the person responsible for is listed below :

- [x] Executive summary for milestone report.                                                          - Emirhan
- [x] Summary of personal effort.                                                                               - Everybody
- [x] List and status of deliverables.                                                                           - İrem
- [x] Evaluation of status of deliverables and impacts on the project (Android)    - Ceren
- [x] Evaluation of status of deliverables and impacts on the project (Frontend)  - Ufuk 
- [x] Evaluation of status of deliverables and impacts on the project (Backend)   - Ömer 
- [x] Communication plan                                                                                            - Ömer
- [x] Updated requirements                                                                                          - Emirhan
- [x] Updated project plan                                                                                            - İrem
- [x] API documentation    -Abdullah
- [x] Evaluation of tools and managing the project. (Frontend)    -Mete
- [x] Evaluation of tools and managing the project. (Backend)    -Abdullah 
- [x] Evaluation of tools and managing the project (Android)    -Eray
- [x] UI design (Frontend)    -Altay
- [x] UI design (Android    -Eray
- [x] Scenarios (Frontend)    -Ufuk
- [x] Scenarios (Android)    -Ceren

**Comment by metekurt** [comment]
- Summary of personal effort is added.
- Evaluation of tools and managing the project is updated.

**Comment by irem-ustunboyacioglu** [comment]
- Updated Project Plan is added.
- List and Status Of Deliverables is updated.
- Summary of personal effort is added.

**Comment by abdullah-coskun** [comment]
Evaluation of tools and managing the project is updated.
API documentation is updated.
Summary of personal effort is added.

**Comment by ycerend** [comment]
- Evaluation of the status of deliverables and impacts on the project (Android) is added.

- Scenarios (Android) is added.
- A summary of personal effort is added.

**Comment by omertoptas** [comment]
- Evaluation of the status of deliverables and impacts on the project (Backend) is added.
- A summary of personal effort is added.

**Comment by emirhansarac29** [comment]
- Requirements updated.
- Executive summary part is complete.

**Comment by emirhansarac29** [comment]
- Summary of work done completed

**Comment by ycerend** [comment]
Everybody completed personal effort before the deadline.
