### ISSUE TITLE
FINAL MILESTONE REPORT

### ISSUE THREAD

**Issue by emirhansarac29** [bounswe/bounswe2019group1#530]
Please follow and indicate your works under this issue, also click corresponding parts. Some parts are already done but comprehensive look over is needed.

5 Unit test for each member(Android-Web-Backend):
Android:
- [x] Emirhan
- [ ] Eray
- [x] Ceren

Web:
- [x] Ufuk
- [x] Mete
- [x] Altay

Backend:
- [x] İrem
- [ ] Abdullah
- [ ] İlker
- [ ] Ömer

Create datas for Project: ( 4 user, 5 article , 2 portfolios for each user)
- [x] Emirhan
- [ ] Eray
- [x] Ceren
- [x] Ufuk
- [ ] Mete
- [ ] Altay
- [ ] İrem
- [ ] Abdullah
- [ ] İlker
- [x] Ömer

A) Repository (GitHub) must include at least the following and should be available online on your Github repository:
- [x] Wiki pages that describe your project, research, meetings, and other artifacts
- [x] Requirements
- [x] All software design documents
- [x] User scenarios and mockups
- [x] Project plan
- [x] Issues
- [x] API documentation
- [x] All code (documented, and with unit tests)
- [ ] Database dump and script for restoring it on a database.
- [x] Manuals (user, system)  -- user manual instructs how users can use the system, system manual describes the system requirements and installation.

B) Submission Delivery Package to be submitted as a cd/dvd/usb stick (many are from your repository):
Software:
- [x] Final version of code, documented and including unit tests
- [ ] Packaged web application ( such as .war file or packaged django app), containing backend and web interfaces to be deployed on customer deployment machine
- [x] .apk file containing the Android solution
- [x] "Readme" file that contains instructions on how to deploy and configure your web and Android applications
- [ ] Database dump & configuration file used by code to obtain database path / username / password (make sure to handle all links and paths in your system so that they work on a remote deployment)
- [x] Software documentation (generated as html)
- [x] Milestone reports (1st and 2nd)
- [x] Final Report (as specified in Part C)

C) Final Report -- HARD COPY (Due: 02.01.2020 10:00), which should be also available on Github wiki:
- [x] Final project assessment (Final Milestone -- assesses the whole process such as lessons learned)
- [x] Status of deliverables
- [x] A summary of coding work done by each team member (In tabular format)
- [x] Annotation implementation & W3C standard compliance
- [x] API documentation
- [x] Requirements
- [x] All design documents (diagrams, mockups etc.)
- [x] User manual
- [x] System manual
- [x] Project Plan (simplified version in a report-friendly format)

Miscellaneous:
- [x] Requirements will be updated.(Emirhan)
- [x] Project plan will be revisited.(İrem)
- [x] API documentation will be added to GitHub.(Abdullah)
- [x] Khajiit web page will be added to GitHub main page.(Emirhan)
- [x] How to run will be added to readMe file.(Abdullah)
- [x] User manual will be created.(Emirhan)
- [x] Apk file will be created.(Emirhan)

Task-Person match is in the https://github.com/bounswe/bounswe2019group1/wiki/Meeting-Notes-12-27.12.2019

**Comment by emirhansarac29** [comment]
Requirement elimination is complete for wiki page

**Comment by emirhansarac29** [comment]
2 Unit Test has been added to Android --> validIbanTest() and emailVerificationCheck()

**Comment by emirhansarac29** [comment]
Project assessment Android part is complete. Other sub groups should also fill their respective parts. @abdullah-coskun and @ufukyilmaz
